version: '3'
services:
  web:
      logging:
        options:
          max-size: 10m
      image: nginx:alpine
      volumes:
          - "./.docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
          - "./.docker/etc/ssl:/etc/ssl"
          - "./.docker/etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
          - "./:/var/www"
      ports:
          - "${HTTPS_PORT:-10443}:443"
      environment:
          - NGINX_HOST=${NGINX_HOST}
      command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
      restart: unless-stopped
      healthcheck:
        test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost/ || exit 1"]
        interval: 1m
        timeout: 10s
        retries: 3
      networks:
        - laraquiz
      depends_on:
          - fpm
  fpm:
      logging:
        options:
          max-size: 10m
      build: ./.docker
      restart: unless-stopped
      volumes:
          - "./.docker/etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
          - "./.docker/etc/php/php-fpm.ini:/usr/local/etc/php-fpm.d/www.conf"
          - "./:/var/www"
      networks:
        - laraquiz

  redis:
    image: redis
    networks:
      - laraquiz

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - laraquiz

  composer:
      logging:
        options:
          max-size: 10m
      restart: 'no'
      image: composer:latest
      command: install --no-dev
      volumes:
      - .:/app

networks:
  laraquiz:
    driver: "bridge"
